(() => {
  const buildScenario = (title, task) => {
    const text = `${title} ${task}`.toLowerCase();
    if (/part|material|spare|inventory|lubricant/.test(text)) {
      return "The maintenance-stores team needs an auditable view of parts usage and spend so it can plan stock and investigate unusual consumption.";
    }
    if (/cost|spend|budget|expensive|median|pareto|concentration/.test(text)) {
      return "Operations finance is reviewing maintenance cost and needs a dependable result for budget decisions and exception analysis.";
    }
    if (/downtime|risk|streak|session|failure|corrective|anomal/.test(text)) {
      return "The reliability team is investigating repeated maintenance activity and operational risk so it can prioritize the right equipment.";
    }
    if (/site|monthly|quarter|trend|calendar|date spine/.test(text)) {
      return "Operations leadership needs a consistent performance view across sites and time periods for its management review.";
    }
    if (/duplicate|missing|audit|quality|never maintained|without recorded/.test(text)) {
      return "The data-quality team is checking whether the maintenance records are complete, unique, and safe to use in reporting.";
    }
    return "The fleet analyst needs a clear operational result that can be checked against the source tables and reused in a report.";
  };

  const inferGrain = (title, task) => {
    const text = `${title} ${task}`.toLowerCase();
    if (/one row|executive kpi|fleet size|total maintenance cost|hmr range/.test(text)) return "one summary row";
    if (/site and category|site, category|site-category/.test(text)) return "one row per site and category";
    if (/month.*site|site.*month|inside each month/.test(text)) return "one row per month and site";
    if (/equipment.*session|session.*equipment/.test(text)) return "one row per equipment session";
    if (/by site|for every site|for each site|each site's|at each site|site matrix/.test(text)) return "one row per site";
    if (/by month|per month|monthly/.test(text)) return "one row per calendar month";
    if (/by quarter|quarterly/.test(text)) return "one row per quarter";
    if (/by category|per category|each category/.test(text)) return "one row per material category";
    if (/per equipment|for each equipment|every equipment|each equipment|by equipment|asset risk/.test(text)) return "one row per equipment";
    if (/per order|each order|every order|order list|maintenance order/.test(text)) return "one row per qualifying maintenance order";
    if (/material/.test(text)) return "one row per qualifying material";
    return "one row per qualifying record";
  };

  const make = (level, title, pattern, task, solution, note, hint1, hint2) => ({
    level,
    title,
    pattern,
    scenario: buildScenario(title, task),
    task,
    grain: inferGrain(title, task),
    requirements: [
      `Use the ${pattern} pattern`,
      "Calculate the answer from the three sample tables; do not hard-code result rows",
      "Use the requested filters, grouping, tie-breaks, and sort order exactly"
    ],
    hints: [hint1 || `Identify the required output grain before using ${pattern}.`, hint2 || "Build the query in small parts and verify the row count at each stage."],
    solution,
    note
  });

  const B = (title, pattern, task, solution, note, h1, h2) => make("Beginner", title, pattern, task, solution, note, h1, h2);
  const I = (title, pattern, task, solution, note, h1, h2) => make("Intermediate", title, pattern, task, solution, note, h1, h2);
  const E = (title, pattern, task, solution, note, h1, h2) => make("Expert", title, pattern, task, solution, note, h1, h2);
  const H = (title, pattern, task, solution, note, h1, h2) => make("Hardest", title, pattern, task, solution, note, h1, h2);

  const beginner = [
    B("Inspect the fleet", "SELECT", "Return every equipment row, ordered by equipment_id.", `SELECT * FROM equipment ORDER BY equipment_id;`, "A stable key-based order makes the result easy to verify."),
    B("Essential equipment columns", "Column selection", "Return equipment_id, equipment_name, model, and site.", `SELECT equipment_id, equipment_name, model, site FROM equipment ORDER BY equipment_id;`, "Selecting only useful fields reduces noise and data transfer."),
    B("Durgapur assets", "WHERE", "List equipment assigned to Durgapur.", `SELECT equipment_id, equipment_name, model FROM equipment WHERE site = 'Durgapur' ORDER BY equipment_id;`, "WHERE limits the population before presentation."),
    B("Active fleet", "Equality filter", "Return all Active equipment with its site and total_hmr.", `SELECT equipment_id, site, total_hmr FROM equipment WHERE status = 'Active' ORDER BY equipment_id;`, "Exact filters are the foundation of reproducible reporting."),
    B("High-hour equipment", "Numeric filter", "Find equipment with total_hmr of at least 10000.", `SELECT equipment_id, equipment_name, total_hmr FROM equipment WHERE total_hmr >= 10000 ORDER BY total_hmr DESC;`, "The filter defines the threshold and ordering shows priority."),
    B("Top three by HMR", "ORDER BY + LIMIT", "Return the three equipment records with the highest total_hmr.", `SELECT equipment_id, equipment_name, total_hmr FROM equipment ORDER BY total_hmr DESC, equipment_id LIMIT 3;`, "A secondary key keeps tied results deterministic."),
    B("Operating sites", "DISTINCT", "Return the unique site names in alphabetical order.", `SELECT DISTINCT site FROM equipment ORDER BY site;`, "DISTINCT changes the grain from equipment to unique site."),
    B("Loader search", "LIKE", "Find equipment names containing the word Loader.", `SELECT equipment_id, equipment_name, model FROM equipment WHERE equipment_name LIKE '%Loader%' ORDER BY equipment_id;`, "Wildcard matching is useful for controlled text exploration."),
    B("Unavailable equipment", "Not equal", "Return equipment that is not Active.", `SELECT equipment_id, equipment_name, status FROM equipment WHERE status <> 'Active' ORDER BY equipment_id;`, "The inequality operator isolates exceptions."),
    B("Two-site filter", "IN", "Return equipment from Durgapur or Odisha.", `SELECT equipment_id, site, status FROM equipment WHERE site IN ('Durgapur', 'Odisha') ORDER BY site, equipment_id;`, "IN is cleaner than repeated OR conditions."),
    B("Mid-life HMR band", "BETWEEN", "Return equipment with total_hmr between 7000 and 12000 inclusive.", `SELECT equipment_id, equipment_name, total_hmr FROM equipment WHERE total_hmr BETWEEN 7000 AND 12000 ORDER BY total_hmr;`, "BETWEEN includes both boundary values."),
    B("HMR risk labels", "CASE", "Classify equipment as High when total_hmr >= 10000, Medium when >= 7000, otherwise Low.", `SELECT equipment_id, total_hmr, CASE WHEN total_hmr >= 10000 THEN 'High' WHEN total_hmr >= 7000 THEN 'Medium' ELSE 'Low' END AS hmr_band FROM equipment ORDER BY total_hmr DESC;`, "CASE translates numeric rules into business labels."),
    B("Readable asset label", "String expression", "Create asset_label as equipment_id, a hyphen, and equipment_name.", `SELECT equipment_id || ' - ' || equipment_name AS asset_label, site FROM equipment ORDER BY equipment_id;`, "Concatenation can build compact labels for reports."),
    B("Fleet size", "COUNT", "Return the total number of registered equipment records.", `SELECT COUNT(*) AS fleet_size FROM equipment;`, "COUNT(*) measures the row population at the current grain."),
    B("Fleet by site", "GROUP BY", "Count equipment by site.", `SELECT site, COUNT(*) AS equipment_count FROM equipment GROUP BY site ORDER BY equipment_count DESC, site;`, "GROUP BY changes the result grain to one row per site."),
    B("Average HMR by site", "AVG + GROUP BY", "Calculate average total_hmr for every site, rounded to two decimals.", `SELECT site, ROUND(AVG(total_hmr), 2) AS avg_hmr FROM equipment GROUP BY site ORDER BY avg_hmr DESC;`, "Aggregating by site creates a comparable utilization benchmark."),
    B("Fleet HMR range", "MIN + MAX", "Return the minimum and maximum total_hmr in the fleet.", `SELECT MIN(total_hmr) AS min_hmr, MAX(total_hmr) AS max_hmr FROM equipment;`, "MIN and MAX summarize the observed range."),
    B("Closed work orders", "WHERE", "Return all Closed maintenance orders ordered by newest date.", `SELECT order_id, equipment_id, order_date, cost_inr FROM maintenance_orders WHERE status = 'Closed' ORDER BY order_date DESC, order_id;`, "Filter status before sorting the operational backlog."),
    B("Costly corrective work", "AND conditions", "Find Corrective orders costing more than 50000.", `SELECT order_id, equipment_id, cost_inr, status FROM maintenance_orders WHERE maintenance_type = 'Corrective' AND cost_inr > 50000 ORDER BY cost_inr DESC;`, "AND ensures both business conditions must be true."),
    B("Q2 maintenance orders", "Date range", "Return orders dated from 2026-04-01 through 2026-06-30.", `SELECT order_id, order_date, maintenance_type FROM maintenance_orders WHERE order_date >= '2026-04-01' AND order_date < '2026-07-01' ORDER BY order_date;`, "An exclusive upper date bound is safe for timestamps too."),
    B("Latest order list", "Date sorting", "Return the five most recent maintenance orders.", `SELECT order_id, equipment_id, order_date, status FROM maintenance_orders ORDER BY order_date DESC, order_id DESC LIMIT 5;`, "Descending date order surfaces the newest events."),
    B("Orders by maintenance type", "COUNT + GROUP BY", "Count work orders for each maintenance_type.", `SELECT maintenance_type, COUNT(*) AS order_count FROM maintenance_orders GROUP BY maintenance_type ORDER BY order_count DESC, maintenance_type;`, "This reveals the maintenance mix."),
    B("Total maintenance cost", "SUM", "Return total maintenance cost across all work orders.", `SELECT SUM(cost_inr) AS total_maintenance_cost FROM maintenance_orders;`, "SUM rolls transaction-level cost into one KPI."),
    B("Downtime by work type", "AVG", "Calculate average downtime_hrs by maintenance_type.", `SELECT maintenance_type, ROUND(AVG(downtime_hrs), 2) AS avg_downtime_hrs FROM maintenance_orders GROUP BY maintenance_type ORDER BY avg_downtime_hrs DESC;`, "The average enables comparison across differently sized groups."),
    B("Repeat-maintenance assets", "HAVING", "Return equipment_id values having at least two maintenance orders.", `SELECT equipment_id, COUNT(*) AS order_count FROM maintenance_orders GROUP BY equipment_id HAVING COUNT(*) >= 2 ORDER BY order_count DESC, equipment_id;`, "HAVING filters after aggregation."),
    B("Spare-part line spend", "Calculated column", "Calculate line_spend as quantity multiplied by unit_cost for each part usage row.", `SELECT usage_id, order_id, material, quantity * unit_cost AS line_spend FROM spare_part_usage ORDER BY line_spend DESC, usage_id;`, "Row-level arithmetic creates a reusable commercial measure."),
    B("Spares category usage", "Text filter", "Return usage rows in the Spares category.", `SELECT usage_id, order_id, material, quantity FROM spare_part_usage WHERE category = 'Spares' ORDER BY material, usage_id;`, "Filtering categorical data isolates the required material class."),
    B("Quantity by category", "SUM + GROUP BY", "Calculate total quantity consumed by part category.", `SELECT category, SUM(quantity) AS total_quantity FROM spare_part_usage GROUP BY category ORDER BY total_quantity DESC, category;`, "The result is one row per inventory category."),
    B("Highest unit-cost materials", "Top N", "Return the five usage rows with the highest unit_cost.", `SELECT material, category, unit_cost FROM spare_part_usage ORDER BY unit_cost DESC, material LIMIT 5;`, "Top-N analysis combines sorting and limiting."),
    B("Monthly order volume", "strftime", "Count maintenance orders by calendar month.", `SELECT strftime('%Y-%m', order_date) AS order_month, COUNT(*) AS order_count FROM maintenance_orders GROUP BY order_month ORDER BY order_month;`, "Extracting a reporting month supports time-based aggregation.")
  ];

  const intermediate = [
    I("Equipment work-order detail", "INNER JOIN", "Join equipment to maintenance_orders and return each order with equipment_name and site.", `SELECT mo.order_id, e.equipment_name, e.site, mo.maintenance_type, mo.cost_inr FROM maintenance_orders AS mo JOIN equipment AS e ON e.equipment_id = mo.equipment_id ORDER BY mo.order_date, mo.order_id;`, "The join enriches order facts with asset dimensions."),
    I("All assets with order counts", "LEFT JOIN", "Return every equipment record with its maintenance order count, including zero-order assets.", `SELECT e.equipment_id, e.equipment_name, COUNT(mo.order_id) AS order_count FROM equipment AS e LEFT JOIN maintenance_orders AS mo ON mo.equipment_id = e.equipment_id GROUP BY e.equipment_id, e.equipment_name ORDER BY order_count DESC, e.equipment_id;`, "LEFT JOIN preserves the full equipment population."),
    I("Three-table maintenance detail", "Three-table JOIN", "Return order, equipment, site, material, quantity, and unit_cost for used parts.", `SELECT mo.order_id, e.equipment_name, e.site, spu.material, spu.quantity, spu.unit_cost FROM maintenance_orders AS mo JOIN equipment AS e ON e.equipment_id = mo.equipment_id JOIN spare_part_usage AS spu ON spu.order_id = mo.order_id ORDER BY mo.order_id, spu.usage_id;`, "Each join follows a declared one-to-many relationship."),
    I("Asset maintenance spend", "LEFT JOIN aggregation", "Calculate total maintenance cost per equipment and show zero for assets without orders.", `SELECT e.equipment_id, e.equipment_name, COALESCE(SUM(mo.cost_inr), 0) AS total_cost FROM equipment AS e LEFT JOIN maintenance_orders AS mo ON mo.equipment_id = e.equipment_id GROUP BY e.equipment_id, e.equipment_name ORDER BY total_cost DESC, e.equipment_id;`, "COALESCE converts missing aggregated cost into a business-friendly zero."),
    I("Site maintenance summary", "JOIN + GROUP BY", "Return order_count, total_downtime, and total_cost by site.", `SELECT e.site, COUNT(mo.order_id) AS order_count, SUM(mo.downtime_hrs) AS total_downtime, SUM(mo.cost_inr) AS total_cost FROM equipment AS e JOIN maintenance_orders AS mo ON mo.equipment_id = e.equipment_id GROUP BY e.site ORDER BY total_cost DESC;`, "Joining before aggregation attributes each order to its operating site."),
    I("Parts spend per order", "Aggregate expression", "Calculate parts_spend per order_id from quantity and unit_cost.", `SELECT order_id, SUM(quantity * unit_cost) AS parts_spend FROM spare_part_usage GROUP BY order_id ORDER BY parts_spend DESC, order_id;`, "Aggregate the line calculation at order grain."),
    I("Material-category spend by site", "Three-table aggregation", "Calculate spare-part spend by site and category.", `SELECT e.site, spu.category, SUM(spu.quantity * spu.unit_cost) AS parts_spend FROM spare_part_usage AS spu JOIN maintenance_orders AS mo ON mo.order_id = spu.order_id JOIN equipment AS e ON e.equipment_id = mo.equipment_id GROUP BY e.site, spu.category ORDER BY e.site, parts_spend DESC;`, "The output grain is explicitly site plus category."),
    I("Active assets with closed history", "EXISTS", "Return Active equipment having at least one Closed order.", `SELECT e.equipment_id, e.equipment_name, e.site FROM equipment AS e WHERE e.status = 'Active' AND EXISTS (SELECT 1 FROM maintenance_orders AS mo WHERE mo.equipment_id = e.equipment_id AND mo.status = 'Closed') ORDER BY e.equipment_id;`, "EXISTS tests a relationship without duplicating outer rows."),
    I("Assets never maintained", "NOT EXISTS", "Return equipment with no maintenance order.", `SELECT e.equipment_id, e.equipment_name, e.site FROM equipment AS e WHERE NOT EXISTS (SELECT 1 FROM maintenance_orders AS mo WHERE mo.equipment_id = e.equipment_id) ORDER BY e.equipment_id;`, "NOT EXISTS expresses an anti-join safely."),
    I("Corrective-maintenance population", "IN subquery", "Return equipment that appears in at least one Corrective order.", `SELECT equipment_id, equipment_name, site FROM equipment WHERE equipment_id IN (SELECT equipment_id FROM maintenance_orders WHERE maintenance_type = 'Corrective') ORDER BY equipment_id;`, "The subquery produces the qualifying asset keys."),
    I("Above-average fleet HMR", "Scalar subquery", "Return equipment whose total_hmr is above the fleet average.", `SELECT equipment_id, equipment_name, total_hmr FROM equipment WHERE total_hmr > (SELECT AVG(total_hmr) FROM equipment) ORDER BY total_hmr DESC;`, "A scalar subquery supplies one comparison benchmark."),
    I("Above-average work-order cost", "Scalar subquery", "Return orders costing more than the average order cost.", `SELECT order_id, equipment_id, cost_inr FROM maintenance_orders WHERE cost_inr > (SELECT AVG(cost_inr) FROM maintenance_orders) ORDER BY cost_inr DESC;`, "The fleet-wide order average defines the exception threshold."),
    I("Cost above asset history", "Correlated subquery", "Return orders costing more than the average for the same equipment.", `SELECT mo.order_id, mo.equipment_id, mo.cost_inr FROM maintenance_orders AS mo WHERE mo.cost_inr > (SELECT AVG(mo2.cost_inr) FROM maintenance_orders AS mo2 WHERE mo2.equipment_id = mo.equipment_id) ORDER BY mo.cost_inr DESC;`, "Correlation creates an asset-specific benchmark."),
    I("Premium parts within category", "Correlated subquery", "Return part rows whose unit_cost is above their category average.", `SELECT spu.usage_id, spu.material, spu.category, spu.unit_cost FROM spare_part_usage AS spu WHERE spu.unit_cost > (SELECT AVG(spu2.unit_cost) FROM spare_part_usage AS spu2 WHERE spu2.category = spu.category) ORDER BY spu.category, spu.unit_cost DESC;`, "Each part is compared with peers from the same category."),
    I("Latest order date per asset", "Correlated MAX", "Return the latest maintenance order for each equipment with order history.", `SELECT mo.order_id, mo.equipment_id, mo.order_date, mo.status FROM maintenance_orders AS mo WHERE mo.order_date = (SELECT MAX(mo2.order_date) FROM maintenance_orders AS mo2 WHERE mo2.equipment_id = mo.equipment_id) ORDER BY mo.equipment_id;`, "The correlated maximum selects the latest date inside each asset group."),
    I("Orders without recorded parts", "Anti-join", "Return maintenance orders having no spare_part_usage row.", `SELECT mo.order_id, mo.equipment_id, mo.maintenance_type FROM maintenance_orders AS mo LEFT JOIN spare_part_usage AS spu ON spu.order_id = mo.order_id WHERE spu.order_id IS NULL ORDER BY mo.order_id;`, "A null match after LEFT JOIN identifies missing relationships."),
    I("Closed-order CTE", "Single CTE", "Use a CTE to isolate Closed orders, then return those costing at least 30000.", `WITH closed_orders AS (SELECT * FROM maintenance_orders WHERE status = 'Closed') SELECT order_id, equipment_id, cost_inr FROM closed_orders WHERE cost_inr >= 30000 ORDER BY cost_inr DESC;`, "The CTE gives the business population a clear name."),
    I("Q2 site-cost pipeline", "Multi-stage CTE", "Use CTEs to filter Q2 Closed orders and summarize cost by site.", `WITH q2_closed AS (SELECT * FROM maintenance_orders WHERE status = 'Closed' AND order_date >= '2026-04-01' AND order_date < '2026-07-01'), site_cost AS (SELECT e.site, SUM(q.cost_inr) AS total_cost FROM q2_closed AS q JOIN equipment AS e ON e.equipment_id = q.equipment_id GROUP BY e.site) SELECT * FROM site_cost ORDER BY total_cost DESC;`, "Separate filtering from aggregation so each stage can be tested."),
    I("Part-spend CTE", "Pre-aggregation CTE", "Aggregate parts to order grain before joining them to maintenance orders.", `WITH parts_by_order AS (SELECT order_id, SUM(quantity * unit_cost) AS parts_spend FROM spare_part_usage GROUP BY order_id) SELECT mo.order_id, mo.equipment_id, COALESCE(p.parts_spend, 0) AS parts_spend FROM maintenance_orders AS mo LEFT JOIN parts_by_order AS p ON p.order_id = mo.order_id ORDER BY parts_spend DESC, mo.order_id;`, "Pre-aggregation aligns the join grain and preserves no-part orders."),
    I("Site status matrix", "Conditional aggregation", "Count Closed, Open, and In Progress orders by site.", `SELECT e.site, SUM(CASE WHEN mo.status = 'Closed' THEN 1 ELSE 0 END) AS closed_orders, SUM(CASE WHEN mo.status = 'Open' THEN 1 ELSE 0 END) AS open_orders, SUM(CASE WHEN mo.status = 'In Progress' THEN 1 ELSE 0 END) AS in_progress_orders FROM equipment AS e JOIN maintenance_orders AS mo ON mo.equipment_id = e.equipment_id GROUP BY e.site ORDER BY e.site;`, "Conditional sums create multiple KPIs in one grouped result."),
    I("Order cost bands", "CASE aggregation", "Classify orders as High (>=75000), Medium (>=25000), or Low, then count each band.", `WITH banded AS (SELECT CASE WHEN cost_inr >= 75000 THEN 'High' WHEN cost_inr >= 25000 THEN 'Medium' ELSE 'Low' END AS cost_band FROM maintenance_orders) SELECT cost_band, COUNT(*) AS order_count FROM banded GROUP BY cost_band ORDER BY order_count DESC, cost_band;`, "Band first, aggregate second."),
    I("Fleet availability union", "UNION ALL", "Combine Active and Maintenance equipment into one labeled population using UNION ALL.", `SELECT equipment_id, equipment_name, 'Available' AS availability FROM equipment WHERE status = 'Active' UNION ALL SELECT equipment_id, equipment_name, 'Unavailable' AS availability FROM equipment WHERE status = 'Maintenance' ORDER BY equipment_id;`, "UNION ALL preserves every row because the populations do not overlap."),
    I("Monthly maintenance cost", "Date aggregation", "Calculate order count and total cost by month.", `SELECT strftime('%Y-%m', order_date) AS order_month, COUNT(*) AS order_count, SUM(cost_inr) AS total_cost FROM maintenance_orders GROUP BY order_month ORDER BY order_month;`, "Month-level aggregation supports trend reporting."),
    I("Quarterly cost summary", "CASE + date", "Classify orders into 2026-Q2 or 2026-Q3 and summarize cost.", `SELECT CASE WHEN order_date < '2026-07-01' THEN '2026-Q2' ELSE '2026-Q3' END AS quarter, COUNT(*) AS order_count, SUM(cost_inr) AS total_cost FROM maintenance_orders GROUP BY quarter ORDER BY quarter;`, "A date rule creates the reporting quarter dimension."),
    I("Maintained assets per site", "COUNT DISTINCT", "Count distinct equipment with at least one maintenance order at each site.", `SELECT e.site, COUNT(DISTINCT mo.equipment_id) AS maintained_assets FROM equipment AS e JOIN maintenance_orders AS mo ON mo.equipment_id = e.equipment_id GROUP BY e.site ORDER BY maintained_assets DESC, e.site;`, "COUNT DISTINCT prevents repeat orders from multiplying the asset count."),
    I("Asset share of site cost", "Subquery join", "Return each equipment total cost and its percentage of the site's cost.", `WITH asset_cost AS (SELECT e.site, e.equipment_id, SUM(mo.cost_inr) AS asset_cost FROM equipment AS e JOIN maintenance_orders AS mo ON mo.equipment_id = e.equipment_id GROUP BY e.site, e.equipment_id), site_cost AS (SELECT site, SUM(asset_cost) AS site_cost FROM asset_cost GROUP BY site) SELECT a.site, a.equipment_id, a.asset_cost, ROUND(100.0 * a.asset_cost / s.site_cost, 2) AS site_cost_pct FROM asset_cost AS a JOIN site_cost AS s ON s.site = a.site ORDER BY a.site, site_cost_pct DESC;`, "Aggregate at both grains before calculating the percentage."),
    I("High-average-cost sites", "HAVING + subquery", "Return sites whose average order cost exceeds the global average order cost.", `SELECT e.site, ROUND(AVG(mo.cost_inr), 2) AS site_avg_cost FROM equipment AS e JOIN maintenance_orders AS mo ON mo.equipment_id = e.equipment_id GROUP BY e.site HAVING AVG(mo.cost_inr) > (SELECT AVG(cost_inr) FROM maintenance_orders) ORDER BY site_avg_cost DESC;`, "HAVING compares grouped metrics with a scalar benchmark."),
    I("High-spend equipment", "HAVING", "Return equipment with total maintenance cost above 100000.", `SELECT e.equipment_id, e.equipment_name, SUM(mo.cost_inr) AS total_cost FROM equipment AS e JOIN maintenance_orders AS mo ON mo.equipment_id = e.equipment_id GROUP BY e.equipment_id, e.equipment_name HAVING SUM(mo.cost_inr) > 100000 ORDER BY total_cost DESC;`, "HAVING filters aggregated asset totals."),
    I("High-parts-spend orders", "CTE + HAVING", "Return orders whose calculated parts spend exceeds 20000.", `WITH parts_by_order AS (SELECT order_id, SUM(quantity * unit_cost) AS parts_spend FROM spare_part_usage GROUP BY order_id HAVING SUM(quantity * unit_cost) > 20000) SELECT order_id, parts_spend FROM parts_by_order ORDER BY parts_spend DESC;`, "The threshold is evaluated at order grain."),
    I("Grain-safe order economics", "Pre-aggregate then join", "Return each order with downtime, maintenance cost, and total parts spend without duplicating order facts.", `WITH parts_by_order AS (SELECT order_id, SUM(quantity * unit_cost) AS parts_spend FROM spare_part_usage GROUP BY order_id) SELECT mo.order_id, mo.downtime_hrs, mo.cost_inr, COALESCE(p.parts_spend, 0) AS parts_spend FROM maintenance_orders AS mo LEFT JOIN parts_by_order AS p ON p.order_id = mo.order_id ORDER BY mo.order_id;`, "One row per order is preserved before any higher-level aggregation.")
  ];

  const expert = [
    E("Costliest order per site", "ROW_NUMBER", "Return the highest-cost maintenance order in each site.", `WITH ranked AS (SELECT e.site, mo.order_id, mo.equipment_id, mo.cost_inr, ROW_NUMBER() OVER (PARTITION BY e.site ORDER BY mo.cost_inr DESC, mo.order_date DESC) AS rn FROM maintenance_orders AS mo JOIN equipment AS e ON e.equipment_id = mo.equipment_id) SELECT site, order_id, equipment_id, cost_inr FROM ranked WHERE rn = 1 ORDER BY site;`, "Window ranking preserves detail while selecting one record per site."),
    E("Top two orders per site", "ROW_NUMBER", "Return the two highest-cost orders within every site.", `WITH ranked AS (SELECT e.site, mo.order_id, mo.cost_inr, ROW_NUMBER() OVER (PARTITION BY e.site ORDER BY mo.cost_inr DESC, mo.order_id) AS rn FROM maintenance_orders AS mo JOIN equipment AS e ON e.equipment_id = mo.equipment_id) SELECT site, order_id, cost_inr, rn FROM ranked WHERE rn <= 2 ORDER BY site, rn;`, "Filtering the window rank creates a top-N-per-group result."),
    E("HMR rank within site", "RANK", "Rank equipment by total_hmr inside each site.", `SELECT site, equipment_id, total_hmr, RANK() OVER (PARTITION BY site ORDER BY total_hmr DESC) AS hmr_rank FROM equipment ORDER BY site, hmr_rank, equipment_id;`, "RANK gives tied assets the same position and leaves gaps."),
    E("Dense cost rank", "DENSE_RANK", "Dense-rank all maintenance orders by cost_inr descending.", `SELECT order_id, cost_inr, DENSE_RANK() OVER (ORDER BY cost_inr DESC) AS cost_rank FROM maintenance_orders ORDER BY cost_rank, order_id;`, "DENSE_RANK does not skip rank values after ties."),
    E("Previous order cost", "LAG", "For each equipment, show every order and the cost of its previous order.", `SELECT equipment_id, order_id, order_date, cost_inr, LAG(cost_inr) OVER (PARTITION BY equipment_id ORDER BY order_date, order_id) AS previous_cost FROM maintenance_orders ORDER BY equipment_id, order_date;`, "LAG compares a row with its preceding event."),
    E("Next maintenance date", "LEAD", "Show the next order date for every equipment order.", `SELECT equipment_id, order_id, order_date, LEAD(order_date) OVER (PARTITION BY equipment_id ORDER BY order_date, order_id) AS next_order_date FROM maintenance_orders ORDER BY equipment_id, order_date;`, "LEAD exposes the next event without a self-join."),
    E("Running site cost", "Running SUM", "Calculate cumulative maintenance cost by site in order-date sequence.", `SELECT e.site, mo.order_id, mo.order_date, mo.cost_inr, SUM(mo.cost_inr) OVER (PARTITION BY e.site ORDER BY mo.order_date, mo.order_id ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running_site_cost FROM maintenance_orders AS mo JOIN equipment AS e ON e.equipment_id = mo.equipment_id ORDER BY e.site, mo.order_date;`, "An explicit ROWS frame makes the running calculation deterministic."),
    E("Cumulative asset downtime", "Window SUM", "Calculate cumulative downtime for each equipment across its orders.", `SELECT equipment_id, order_id, order_date, downtime_hrs, SUM(downtime_hrs) OVER (PARTITION BY equipment_id ORDER BY order_date, order_id ROWS UNBOUNDED PRECEDING) AS cumulative_downtime FROM maintenance_orders ORDER BY equipment_id, order_date;`, "Partitioning resets the cumulative total for each asset."),
    E("Three-order moving cost", "Moving AVG", "Calculate a three-order moving average cost across chronological fleet orders.", `SELECT order_id, order_date, cost_inr, ROUND(AVG(cost_inr) OVER (ORDER BY order_date, order_id ROWS BETWEEN 2 PRECEDING AND CURRENT ROW), 2) AS moving_avg_3 FROM maintenance_orders ORDER BY order_date, order_id;`, "A bounded window smooths short-term cost movement."),
    E("Order share of site cost", "Window percentage", "Calculate each order's percentage contribution to total cost at its site.", `SELECT e.site, mo.order_id, mo.cost_inr, ROUND(100.0 * mo.cost_inr / SUM(mo.cost_inr) OVER (PARTITION BY e.site), 2) AS site_cost_pct FROM maintenance_orders AS mo JOIN equipment AS e ON e.equipment_id = mo.equipment_id ORDER BY e.site, site_cost_pct DESC;`, "A partition total keeps order detail while adding site context."),
    E("First order per equipment", "ROW_NUMBER", "Return the earliest order for each equipment with history.", `WITH ranked AS (SELECT mo.*, ROW_NUMBER() OVER (PARTITION BY equipment_id ORDER BY order_date, order_id) AS rn FROM maintenance_orders AS mo) SELECT equipment_id, order_id, order_date, maintenance_type FROM ranked WHERE rn = 1 ORDER BY equipment_id;`, "Ranking provides an explicit and tie-safe first-event rule."),
    E("Latest full order row", "ROW_NUMBER", "Return the latest complete order record for each equipment.", `WITH ranked AS (SELECT mo.*, ROW_NUMBER() OVER (PARTITION BY equipment_id ORDER BY order_date DESC, order_id DESC) AS rn FROM maintenance_orders AS mo) SELECT equipment_id, order_id, order_date, status, cost_inr FROM ranked WHERE rn = 1 ORDER BY equipment_id;`, "The window method returns columns from the same latest row."),
    E("Second-costliest order per site", "DENSE_RANK", "Return the second distinct highest order cost in each site.", `WITH ranked AS (SELECT e.site, mo.order_id, mo.cost_inr, DENSE_RANK() OVER (PARTITION BY e.site ORDER BY mo.cost_inr DESC) AS cost_rank FROM maintenance_orders AS mo JOIN equipment AS e ON e.equipment_id = mo.equipment_id) SELECT site, order_id, cost_inr FROM ranked WHERE cost_rank = 2 ORDER BY site, order_id;`, "DENSE_RANK correctly handles tied cost values."),
    E("Order-cost quartiles", "NTILE", "Assign every order to one of four cost quartiles.", `SELECT order_id, cost_inr, NTILE(4) OVER (ORDER BY cost_inr DESC, order_id) AS cost_quartile FROM maintenance_orders ORDER BY cost_quartile, cost_inr DESC;`, "NTILE divides the ordered population into near-equal buckets."),
    E("Relative cost position", "PERCENT_RANK", "Calculate the relative cost rank of every order.", `SELECT order_id, cost_inr, ROUND(PERCENT_RANK() OVER (ORDER BY cost_inr), 4) AS cost_percent_rank FROM maintenance_orders ORDER BY cost_inr;`, "PERCENT_RANK locates each row between the minimum and maximum ranks."),
    E("Cumulative cost distribution", "CUME_DIST", "Calculate cumulative distribution by order cost.", `SELECT order_id, cost_inr, ROUND(CUME_DIST() OVER (ORDER BY cost_inr), 4) AS cumulative_distribution FROM maintenance_orders ORDER BY cost_inr;`, "CUME_DIST shows the fraction of rows at or below each cost."),
    E("Generate a sequence", "Recursive CTE", "Generate integers 1 through 10 using a recursive CTE.", `WITH RECURSIVE numbers(n) AS (SELECT 1 UNION ALL SELECT n + 1 FROM numbers WHERE n < 10) SELECT n FROM numbers;`, "Recursive CTEs can construct rows that do not exist in a source table."),
    E("Monthly maintenance calendar", "Recursive calendar CTE", "Generate months April through July 2026 and left join monthly order counts.", `WITH RECURSIVE months(month_start) AS (SELECT date('2026-04-01') UNION ALL SELECT date(month_start, '+1 month') FROM months WHERE month_start < '2026-07-01'), monthly_orders AS (SELECT date(order_date, 'start of month') AS month_start, COUNT(*) AS order_count FROM maintenance_orders GROUP BY date(order_date, 'start of month')) SELECT m.month_start, COALESCE(o.order_count, 0) AS order_count FROM months AS m LEFT JOIN monthly_orders AS o ON o.month_start = m.month_start ORDER BY m.month_start;`, "A date spine makes zero-activity periods visible."),
    E("Site-month zero fill", "CROSS JOIN matrix", "Create every site-month combination for April through July and show zero when no order exists.", `WITH RECURSIVE months(month_start) AS (SELECT date('2026-04-01') UNION ALL SELECT date(month_start, '+1 month') FROM months WHERE month_start < '2026-07-01'), sites AS (SELECT DISTINCT site FROM equipment), monthly AS (SELECT e.site, date(mo.order_date, 'start of month') AS month_start, COUNT(*) AS order_count FROM maintenance_orders AS mo JOIN equipment AS e ON e.equipment_id = mo.equipment_id GROUP BY e.site, date(mo.order_date, 'start of month')) SELECT s.site, m.month_start, COALESCE(x.order_count, 0) AS order_count FROM sites AS s CROSS JOIN months AS m LEFT JOIN monthly AS x ON x.site = s.site AND x.month_start = m.month_start ORDER BY s.site, m.month_start;`, "Build the complete dimensional grid before attaching observed facts."),
    E("Cost change from prior order", "LAG + CTE", "Calculate absolute and percentage cost change from the previous fleet order.", `WITH sequenced AS (SELECT order_id, order_date, cost_inr, LAG(cost_inr) OVER (ORDER BY order_date, order_id) AS previous_cost FROM maintenance_orders) SELECT order_id, order_date, cost_inr, previous_cost, cost_inr - previous_cost AS cost_change, ROUND(100.0 * (cost_inr - previous_cost) / previous_cost, 2) AS cost_change_pct FROM sequenced ORDER BY order_date, order_id;`, "Sequence first, then calculate change using the lagged value."),
    E("Days between asset orders", "LAG + julianday", "Calculate days since the previous maintenance order for each equipment.", `WITH sequenced AS (SELECT equipment_id, order_id, order_date, LAG(order_date) OVER (PARTITION BY equipment_id ORDER BY order_date, order_id) AS previous_date FROM maintenance_orders) SELECT equipment_id, order_id, order_date, previous_date, CAST(julianday(order_date) - julianday(previous_date) AS INTEGER) AS gap_days FROM sequenced ORDER BY equipment_id, order_date;`, "Date arithmetic converts adjacent events into maintenance intervals."),
    E("Longest maintenance gap", "Window + aggregate", "Return the longest observed order gap for each equipment with repeat history.", `WITH sequenced AS (SELECT equipment_id, order_date, LAG(order_date) OVER (PARTITION BY equipment_id ORDER BY order_date) AS previous_date FROM maintenance_orders), gaps AS (SELECT equipment_id, CAST(julianday(order_date) - julianday(previous_date) AS INTEGER) AS gap_days FROM sequenced WHERE previous_date IS NOT NULL) SELECT equipment_id, MAX(gap_days) AS longest_gap_days FROM gaps GROUP BY equipment_id ORDER BY longest_gap_days DESC, equipment_id;`, "Calculate event-level gaps before aggregating their maximum."),
    E("Trailing 30-day order cost", "Correlated date window", "For every order, calculate total fleet order cost in the preceding 30 days including that date.", `SELECT mo.order_id, mo.order_date, mo.cost_inr, (SELECT SUM(mo2.cost_inr) FROM maintenance_orders AS mo2 WHERE mo2.order_date BETWEEN date(mo.order_date, '-30 days') AND mo.order_date) AS trailing_30_day_cost FROM maintenance_orders AS mo ORDER BY mo.order_date, mo.order_id;`, "A correlated date range creates a calendar-based rolling measure."),
    E("Running category parts spend", "Window aggregate", "Calculate cumulative parts spend inside each category ordered by usage_id.", `SELECT category, usage_id, material, quantity * unit_cost AS line_spend, SUM(quantity * unit_cost) OVER (PARTITION BY category ORDER BY usage_id ROWS UNBOUNDED PRECEDING) AS running_category_spend FROM spare_part_usage ORDER BY category, usage_id;`, "The running total resets for every material category."),
    E("Pareto material spend", "Cumulative share", "Aggregate spend by material and calculate cumulative percentage from highest to lowest.", `WITH material_spend AS (SELECT material, SUM(quantity * unit_cost) AS spend FROM spare_part_usage GROUP BY material), ranked AS (SELECT material, spend, SUM(spend) OVER (ORDER BY spend DESC, material ROWS UNBOUNDED PRECEDING) AS cumulative_spend, SUM(spend) OVER () AS total_spend FROM material_spend) SELECT material, spend, ROUND(100.0 * cumulative_spend / total_spend, 2) AS cumulative_pct FROM ranked ORDER BY spend DESC, material;`, "Aggregate before applying the Pareto window."),
    E("Median order cost", "Median with windows", "Calculate the median maintenance order cost without a MEDIAN function.", `WITH ordered AS (SELECT cost_inr, ROW_NUMBER() OVER (ORDER BY cost_inr) AS rn, COUNT(*) OVER () AS cnt FROM maintenance_orders) SELECT AVG(cost_inr) AS median_cost FROM ordered WHERE rn IN ((cnt + 1) / 2, (cnt + 2) / 2);`, "The middle one or two rows determine the median."),
    E("Median cost by site", "Partitioned median", "Calculate the median order cost separately for each site.", `WITH ordered AS (SELECT e.site, mo.cost_inr, ROW_NUMBER() OVER (PARTITION BY e.site ORDER BY mo.cost_inr) AS rn, COUNT(*) OVER (PARTITION BY e.site) AS cnt FROM maintenance_orders AS mo JOIN equipment AS e ON e.equipment_id = mo.equipment_id) SELECT site, AVG(cost_inr) AS median_cost FROM ordered WHERE rn IN ((cnt + 1) / 2, (cnt + 2) / 2) GROUP BY site ORDER BY site;`, "Partitioned counts identify the correct middle rows within each site."),
    E("Most common work type by site", "Mode with ranking", "Return the most frequent maintenance_type at each site, preserving ties.", `WITH counts AS (SELECT e.site, mo.maintenance_type, COUNT(*) AS type_count FROM maintenance_orders AS mo JOIN equipment AS e ON e.equipment_id = mo.equipment_id GROUP BY e.site, mo.maintenance_type), ranked AS (SELECT *, DENSE_RANK() OVER (PARTITION BY site ORDER BY type_count DESC) AS rnk FROM counts) SELECT site, maintenance_type, type_count FROM ranked WHERE rnk = 1 ORDER BY site, maintenance_type;`, "Count categories first, then rank the counts."),
    E("Maintenance-type pivot", "Conditional pivot", "Create one row per site with Preventive, Corrective, and Inspection order counts.", `SELECT e.site, SUM(CASE WHEN mo.maintenance_type = 'Preventive' THEN 1 ELSE 0 END) AS preventive, SUM(CASE WHEN mo.maintenance_type = 'Corrective' THEN 1 ELSE 0 END) AS corrective, SUM(CASE WHEN mo.maintenance_type = 'Inspection' THEN 1 ELSE 0 END) AS inspection FROM maintenance_orders AS mo JOIN equipment AS e ON e.equipment_id = mo.equipment_id GROUP BY e.site ORDER BY e.site;`, "Conditional aggregation is a portable pivot technique."),
    E("Grain-safe site dashboard", "Multi-stage aggregation", "Return site order count, downtime, maintenance cost, and parts spend without fan-out.", `WITH parts_by_order AS (SELECT order_id, SUM(quantity * unit_cost) AS parts_spend FROM spare_part_usage GROUP BY order_id), order_facts AS (SELECT mo.order_id, mo.equipment_id, mo.downtime_hrs, mo.cost_inr, COALESCE(p.parts_spend, 0) AS parts_spend FROM maintenance_orders AS mo LEFT JOIN parts_by_order AS p ON p.order_id = mo.order_id) SELECT e.site, COUNT(o.order_id) AS order_count, SUM(o.downtime_hrs) AS total_downtime, SUM(o.cost_inr) AS maintenance_cost, SUM(o.parts_spend) AS parts_spend FROM order_facts AS o JOIN equipment AS e ON e.equipment_id = o.equipment_id GROUP BY e.site ORDER BY maintenance_cost DESC;`, "Every fact is aligned to one row per order before site aggregation.")
  ];

  const hardest = [
    H("Consecutive maintenance months", "Gaps and islands", "Group consecutive fleet maintenance months into continuous islands.", `WITH months AS (SELECT DISTINCT date(order_date, 'start of month') AS month_start FROM maintenance_orders), numbered AS (SELECT month_start, ROW_NUMBER() OVER (ORDER BY month_start) AS rn FROM months), grouped AS (SELECT month_start, date(month_start, printf('-%d month', rn)) AS island_key FROM numbered) SELECT MIN(month_start) AS island_start, MAX(month_start) AS island_end, COUNT(*) AS month_count FROM grouped GROUP BY island_key ORDER BY island_start;`, "Subtracting a row-number interval gives consecutive dates the same island key."),
    H("Back-to-back corrective orders", "LAG condition", "Find orders where the same equipment's immediately previous order was also Corrective.", `WITH sequenced AS (SELECT equipment_id, order_id, order_date, maintenance_type, LAG(maintenance_type) OVER (PARTITION BY equipment_id ORDER BY order_date, order_id) AS previous_type FROM maintenance_orders) SELECT equipment_id, order_id, order_date FROM sequenced WHERE maintenance_type = 'Corrective' AND previous_type = 'Corrective' ORDER BY equipment_id, order_date;`, "The lagged type exposes adjacent corrective events."),
    H("Longest corrective streak", "Gaps and islands", "Calculate the longest consecutive Corrective-order streak for each equipment.", `WITH sequenced AS (SELECT equipment_id, order_id, order_date, maintenance_type, ROW_NUMBER() OVER (PARTITION BY equipment_id ORDER BY order_date, order_id) AS rn_all, ROW_NUMBER() OVER (PARTITION BY equipment_id, maintenance_type ORDER BY order_date, order_id) AS rn_type FROM maintenance_orders), streaks AS (SELECT equipment_id, rn_all - rn_type AS grp, COUNT(*) AS streak_length FROM sequenced WHERE maintenance_type = 'Corrective' GROUP BY equipment_id, rn_all - rn_type) SELECT equipment_id, MAX(streak_length) AS longest_corrective_streak FROM streaks GROUP BY equipment_id ORDER BY longest_corrective_streak DESC, equipment_id;`, "The difference between two row numbers stays constant inside a consecutive run."),
    H("Monthly cost growth", "LAG percentage", "Calculate month-over-month maintenance cost change and percentage.", `WITH monthly AS (SELECT strftime('%Y-%m', order_date) AS month, SUM(cost_inr) AS total_cost FROM maintenance_orders GROUP BY strftime('%Y-%m', order_date)), sequenced AS (SELECT month, total_cost, LAG(total_cost) OVER (ORDER BY month) AS previous_cost FROM monthly) SELECT month, total_cost, previous_cost, total_cost - previous_cost AS cost_change, ROUND(100.0 * (total_cost - previous_cost) / previous_cost, 2) AS growth_pct FROM sequenced ORDER BY month;`, "Aggregate to month grain before applying time-series comparison."),
    H("Asset moving average", "Partitioned moving AVG", "Calculate a two-order moving average cost for each equipment.", `SELECT equipment_id, order_id, order_date, cost_inr, ROUND(AVG(cost_inr) OVER (PARTITION BY equipment_id ORDER BY order_date, order_id ROWS BETWEEN 1 PRECEDING AND CURRENT ROW), 2) AS moving_avg_2 FROM maintenance_orders ORDER BY equipment_id, order_date;`, "The frame contains the current and previous asset order."),
    H("Calendar-based rolling downtime", "RANGE window", "Calculate fleet downtime in the trailing 30 calendar days for each order.", `SELECT order_id, order_date, downtime_hrs, SUM(downtime_hrs) OVER (ORDER BY julianday(order_date) RANGE BETWEEN 30 PRECEDING AND CURRENT ROW) AS trailing_30_day_downtime FROM maintenance_orders ORDER BY order_date, order_id;`, "A numeric date order enables a true calendar-range window."),
    H("Daily Q2 date spine", "Recursive date CTE", "Generate every Q2 date and attach that day's order count and cost.", `WITH RECURSIVE dates(day) AS (SELECT date('2026-04-01') UNION ALL SELECT date(day, '+1 day') FROM dates WHERE day < '2026-06-30'), daily AS (SELECT order_date AS day, COUNT(*) AS order_count, SUM(cost_inr) AS total_cost FROM maintenance_orders GROUP BY order_date) SELECT d.day, COALESCE(x.order_count, 0) AS order_count, COALESCE(x.total_cost, 0) AS total_cost FROM dates AS d LEFT JOIN daily AS x ON x.day = d.day ORDER BY d.day;`, "A recursive date spine guarantees complete time coverage."),
    H("Asset-month activity matrix", "Dimension scaffold", "Create every equipment-month combination from April through July and mark whether maintenance occurred.", `WITH RECURSIVE months(month_start) AS (SELECT date('2026-04-01') UNION ALL SELECT date(month_start, '+1 month') FROM months WHERE month_start < '2026-07-01'), activity AS (SELECT equipment_id, date(order_date, 'start of month') AS month_start, COUNT(*) AS order_count FROM maintenance_orders GROUP BY equipment_id, date(order_date, 'start of month')) SELECT e.equipment_id, m.month_start, COALESCE(a.order_count, 0) AS order_count FROM equipment AS e CROSS JOIN months AS m LEFT JOIN activity AS a ON a.equipment_id = e.equipment_id AND a.month_start = m.month_start ORDER BY e.equipment_id, m.month_start;`, "Scaffolding dimensions first prevents missing zero-activity combinations."),
    H("Assets with preventive and corrective history", "Relational division", "Return assets that have experienced both Preventive and Corrective orders.", `SELECT e.equipment_id, e.equipment_name FROM equipment AS e JOIN maintenance_orders AS mo ON mo.equipment_id = e.equipment_id WHERE mo.maintenance_type IN ('Preventive', 'Corrective') GROUP BY e.equipment_id, e.equipment_name HAVING COUNT(DISTINCT mo.maintenance_type) = 2 ORDER BY e.equipment_id;`, "Counting required distinct types implements relational division compactly."),
    H("All required work types", "Double NOT EXISTS", "Solve the preventive-and-corrective requirement using double NOT EXISTS.", `WITH required_types(type) AS (VALUES ('Preventive'), ('Corrective')) SELECT e.equipment_id, e.equipment_name FROM equipment AS e WHERE NOT EXISTS (SELECT 1 FROM required_types AS r WHERE NOT EXISTS (SELECT 1 FROM maintenance_orders AS mo WHERE mo.equipment_id = e.equipment_id AND mo.maintenance_type = r.type)) ORDER BY e.equipment_id;`, "Double NOT EXISTS literally expresses 'there is no required type that is missing'."),
    H("Site coverage by maintenance type", "Relational division by group", "Return sites that contain every maintenance_type found in the full order table.", `SELECT e.site FROM equipment AS e JOIN maintenance_orders AS mo ON mo.equipment_id = e.equipment_id GROUP BY e.site HAVING COUNT(DISTINCT mo.maintenance_type) = (SELECT COUNT(DISTINCT maintenance_type) FROM maintenance_orders) ORDER BY e.site;`, "Compare each site's distinct coverage with the global required set."),
    H("Orders reaching 80 percent of cost", "Pareto threshold", "Return the highest-cost orders included up to and including the row that crosses 80% of total cost.", `WITH ranked AS (SELECT order_id, cost_inr, SUM(cost_inr) OVER (ORDER BY cost_inr DESC, order_id ROWS UNBOUNDED PRECEDING) AS cumulative_cost, SUM(cost_inr) OVER () AS total_cost FROM maintenance_orders), marked AS (SELECT *, LAG(cumulative_cost, 1, 0) OVER (ORDER BY cost_inr DESC, order_id) AS previous_cumulative FROM ranked) SELECT order_id, cost_inr, ROUND(100.0 * cumulative_cost / total_cost, 2) AS cumulative_pct FROM marked WHERE 1.0 * previous_cumulative / total_cost < 0.80 ORDER BY cost_inr DESC, order_id;`, "Use the prior cumulative value so the boundary-crossing row is retained."),
    H("Costs nearest the median", "Median distance", "Return the three orders whose cost is closest to the fleet median.", `WITH ordered AS (SELECT cost_inr, ROW_NUMBER() OVER (ORDER BY cost_inr) AS rn, COUNT(*) OVER () AS cnt FROM maintenance_orders), median_value AS (SELECT AVG(cost_inr) AS median_cost FROM ordered WHERE rn IN ((cnt + 1) / 2, (cnt + 2) / 2)) SELECT mo.order_id, mo.cost_inr, m.median_cost, ABS(mo.cost_inr - m.median_cost) AS distance_from_median FROM maintenance_orders AS mo CROSS JOIN median_value AS m ORDER BY distance_from_median, mo.order_id LIMIT 3;`, "Derive the median once, then rank every order by absolute distance."),
    H("Robust cost anomalies", "Mean absolute deviation", "Flag orders above the mean plus 1.5 times the mean absolute deviation.", `WITH stats AS (SELECT AVG(cost_inr) AS mean_cost FROM maintenance_orders), deviations AS (SELECT AVG(ABS(mo.cost_inr - s.mean_cost)) AS mad FROM maintenance_orders AS mo CROSS JOIN stats AS s), threshold AS (SELECT s.mean_cost, d.mad, s.mean_cost + 1.5 * d.mad AS anomaly_threshold FROM stats AS s CROSS JOIN deviations AS d) SELECT mo.order_id, mo.cost_inr, ROUND(t.anomaly_threshold, 2) AS anomaly_threshold FROM maintenance_orders AS mo CROSS JOIN threshold AS t WHERE mo.cost_inr > t.anomaly_threshold ORDER BY mo.cost_inr DESC;`, "Mean absolute deviation provides a portable anomaly rule without vendor-specific functions."),
    H("Composite equipment risk score", "Multi-metric CTE", "Score equipment using open-order count, total downtime, and total cost, while preserving zero-order assets.", `WITH metrics AS (SELECT e.equipment_id, e.equipment_name, SUM(CASE WHEN mo.status IN ('Open', 'In Progress') THEN 1 ELSE 0 END) AS unresolved_orders, COALESCE(SUM(mo.downtime_hrs), 0) AS downtime, COALESCE(SUM(mo.cost_inr), 0) AS total_cost FROM equipment AS e LEFT JOIN maintenance_orders AS mo ON mo.equipment_id = e.equipment_id GROUP BY e.equipment_id, e.equipment_name) SELECT equipment_id, equipment_name, unresolved_orders, downtime, total_cost, unresolved_orders * 50 + downtime * 2 + total_cost / 10000.0 AS risk_score FROM metrics ORDER BY risk_score DESC, equipment_id;`, "A staged metric table makes the scoring formula auditable."),
    H("Risk priority within site", "Metric + window rank", "Calculate the composite equipment risk score and rank assets within each site.", `WITH metrics AS (SELECT e.site, e.equipment_id, SUM(CASE WHEN mo.status IN ('Open', 'In Progress') THEN 1 ELSE 0 END) * 50 + COALESCE(SUM(mo.downtime_hrs), 0) * 2 + COALESCE(SUM(mo.cost_inr), 0) / 10000.0 AS risk_score FROM equipment AS e LEFT JOIN maintenance_orders AS mo ON mo.equipment_id = e.equipment_id GROUP BY e.site, e.equipment_id) SELECT site, equipment_id, risk_score, DENSE_RANK() OVER (PARTITION BY site ORDER BY risk_score DESC) AS site_risk_rank FROM metrics ORDER BY site, site_risk_rank, equipment_id;`, "Aggregate risk inputs first, then rank the resulting asset scores."),
    H("Materials used across sites", "COUNT DISTINCT across joins", "Return materials consumed at more than one operating site.", `SELECT spu.material, COUNT(DISTINCT e.site) AS site_count FROM spare_part_usage AS spu JOIN maintenance_orders AS mo ON mo.order_id = spu.order_id JOIN equipment AS e ON e.equipment_id = mo.equipment_id GROUP BY spu.material HAVING COUNT(DISTINCT e.site) > 1 ORDER BY site_count DESC, spu.material;`, "Distinct site counts reveal cross-site material dependence."),
    H("Category spend concentration", "HHI calculation", "Calculate a Herfindahl-style spend concentration index for materials inside each category.", `WITH material_spend AS (SELECT category, material, SUM(quantity * unit_cost) AS spend FROM spare_part_usage GROUP BY category, material), shares AS (SELECT category, material, spend, 1.0 * spend / SUM(spend) OVER (PARTITION BY category) AS spend_share FROM material_spend) SELECT category, ROUND(SUM(spend_share * spend_share), 4) AS concentration_index FROM shares GROUP BY category ORDER BY concentration_index DESC, category;`, "Squaring and summing material shares measures concentration."),
    H("Latest order with top-spend part", "Layered ranking", "For each equipment, return its latest order and the highest-spend part used on that order.", `WITH latest_orders AS (SELECT mo.*, ROW_NUMBER() OVER (PARTITION BY equipment_id ORDER BY order_date DESC, order_id DESC) AS order_rn FROM maintenance_orders AS mo), part_rank AS (SELECT spu.order_id, spu.material, spu.quantity * spu.unit_cost AS line_spend, ROW_NUMBER() OVER (PARTITION BY spu.order_id ORDER BY spu.quantity * spu.unit_cost DESC, spu.usage_id) AS part_rn FROM spare_part_usage AS spu) SELECT l.equipment_id, l.order_id, l.order_date, p.material, p.line_spend FROM latest_orders AS l LEFT JOIN part_rank AS p ON p.order_id = l.order_id AND p.part_rn = 1 WHERE l.order_rn = 1 ORDER BY l.equipment_id;`, "Rank orders and parts independently before combining their winners."),
    H("Highest-parts-spend order per site", "Pre-aggregate + rank", "Return the order with the highest total parts spend at each site.", `WITH parts_by_order AS (SELECT order_id, SUM(quantity * unit_cost) AS parts_spend FROM spare_part_usage GROUP BY order_id), ranked AS (SELECT e.site, mo.order_id, COALESCE(p.parts_spend, 0) AS parts_spend, ROW_NUMBER() OVER (PARTITION BY e.site ORDER BY COALESCE(p.parts_spend, 0) DESC, mo.order_id) AS rn FROM maintenance_orders AS mo JOIN equipment AS e ON e.equipment_id = mo.equipment_id LEFT JOIN parts_by_order AS p ON p.order_id = mo.order_id) SELECT site, order_id, parts_spend FROM ranked WHERE rn = 1 ORDER BY site;`, "Order-level part spend must exist before the site ranking."),
    H("Recursive order chain", "Recursive traversal", "Traverse each equipment's order sequence recursively from first to last.", `WITH RECURSIVE ordered AS (SELECT equipment_id, order_id, order_date, ROW_NUMBER() OVER (PARTITION BY equipment_id ORDER BY order_date, order_id) AS rn FROM maintenance_orders), order_chain(equipment_id, order_id, order_date, rn, path) AS (SELECT equipment_id, order_id, order_date, rn, order_id FROM ordered WHERE rn = 1 UNION ALL SELECT o.equipment_id, o.order_id, o.order_date, o.rn, c.path || ' > ' || o.order_id FROM order_chain AS c JOIN ordered AS o ON o.equipment_id = c.equipment_id AND o.rn = c.rn + 1) SELECT equipment_id, order_id, rn, path FROM order_chain ORDER BY equipment_id, rn;`, "Recursive traversal advances by one row number inside each asset partition."),
    H("Missing order numbers", "Recursive sequence audit", "Generate WO-1001 through WO-1012 and report any missing order IDs.", `WITH RECURSIVE ids(n) AS (SELECT 1001 UNION ALL SELECT n + 1 FROM ids WHERE n < 1012), expected AS (SELECT 'WO-' || n AS order_id FROM ids) SELECT e.order_id FROM expected AS e LEFT JOIN maintenance_orders AS mo ON mo.order_id = e.order_id WHERE mo.order_id IS NULL ORDER BY e.order_id;`, "A generated expected set supports completeness checks."),
    H("Duplicate-order audit", "ROW_NUMBER data quality", "Detect duplicate business keys by retaining rows ranked above one per order_id.", `WITH checked AS (SELECT order_id, equipment_id, order_date, ROW_NUMBER() OVER (PARTITION BY order_id ORDER BY order_date, equipment_id) AS duplicate_rn FROM maintenance_orders) SELECT order_id, equipment_id, order_date FROM checked WHERE duplicate_rn > 1 ORDER BY order_id;`, "A zero-row result confirms the primary business key is unique."),
    H("Maintenance sessions", "Sessionization", "Start a new equipment maintenance session whenever the gap from the prior order exceeds 30 days.", `WITH gaps AS (SELECT equipment_id, order_id, order_date, LAG(order_date) OVER (PARTITION BY equipment_id ORDER BY order_date, order_id) AS previous_date FROM maintenance_orders), flags AS (SELECT *, CASE WHEN previous_date IS NULL OR julianday(order_date) - julianday(previous_date) > 30 THEN 1 ELSE 0 END AS new_session FROM gaps), sessions AS (SELECT *, SUM(new_session) OVER (PARTITION BY equipment_id ORDER BY order_date, order_id ROWS UNBOUNDED PRECEDING) AS session_id FROM flags) SELECT equipment_id, session_id, MIN(order_date) AS session_start, MAX(order_date) AS session_end, COUNT(*) AS order_count FROM sessions GROUP BY equipment_id, session_id ORDER BY equipment_id, session_id;`, "A cumulative sum of boundary flags creates stable session identifiers."),
    H("Longest maintenance session", "Sessionization + ranking", "Return the session containing the most orders for each equipment.", `WITH gaps AS (SELECT equipment_id, order_id, order_date, LAG(order_date) OVER (PARTITION BY equipment_id ORDER BY order_date, order_id) AS previous_date FROM maintenance_orders), flags AS (SELECT *, CASE WHEN previous_date IS NULL OR julianday(order_date) - julianday(previous_date) > 30 THEN 1 ELSE 0 END AS new_session FROM gaps), labeled AS (SELECT *, SUM(new_session) OVER (PARTITION BY equipment_id ORDER BY order_date, order_id) AS session_id FROM flags), summary AS (SELECT equipment_id, session_id, MIN(order_date) AS session_start, MAX(order_date) AS session_end, COUNT(*) AS order_count FROM labeled GROUP BY equipment_id, session_id), ranked AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY equipment_id ORDER BY order_count DESC, session_start) AS rn FROM summary) SELECT equipment_id, session_id, session_start, session_end, order_count FROM ranked WHERE rn = 1 ORDER BY equipment_id;`, "Summarize sessions before ranking them by size."),
    H("Site cost volatility", "Average absolute change", "Measure each site's average absolute change between consecutive order costs.", `WITH sequenced AS (SELECT e.site, mo.order_id, mo.order_date, mo.cost_inr, LAG(mo.cost_inr) OVER (PARTITION BY e.site ORDER BY mo.order_date, mo.order_id) AS previous_cost FROM maintenance_orders AS mo JOIN equipment AS e ON e.equipment_id = mo.equipment_id), changes AS (SELECT site, ABS(cost_inr - previous_cost) AS absolute_change FROM sequenced WHERE previous_cost IS NOT NULL) SELECT site, ROUND(AVG(absolute_change), 2) AS avg_absolute_cost_change FROM changes GROUP BY site ORDER BY avg_absolute_cost_change DESC;`, "Average absolute change is a portable volatility measure."),
    H("Monthly contribution leaders", "Two-level aggregation + rank", "Rank sites by maintenance cost inside each month.", `WITH monthly_site AS (SELECT strftime('%Y-%m', mo.order_date) AS month, e.site, SUM(mo.cost_inr) AS site_cost FROM maintenance_orders AS mo JOIN equipment AS e ON e.equipment_id = mo.equipment_id GROUP BY strftime('%Y-%m', mo.order_date), e.site), ranked AS (SELECT *, DENSE_RANK() OVER (PARTITION BY month ORDER BY site_cost DESC) AS month_rank FROM monthly_site) SELECT month, site, site_cost, month_rank FROM ranked ORDER BY month, month_rank, site;`, "Aggregate the site-month metric before ranking contributors."),
    H("Asset vs site vs fleet benchmark", "Nested benchmarks", "Return every maintained asset with its total cost, site average asset cost, and fleet average asset cost.", `WITH asset_cost AS (SELECT e.site, e.equipment_id, SUM(mo.cost_inr) AS total_cost FROM equipment AS e JOIN maintenance_orders AS mo ON mo.equipment_id = e.equipment_id GROUP BY e.site, e.equipment_id), benchmarked AS (SELECT site, equipment_id, total_cost, AVG(total_cost) OVER (PARTITION BY site) AS site_avg_cost, AVG(total_cost) OVER () AS fleet_avg_cost FROM asset_cost) SELECT site, equipment_id, total_cost, ROUND(site_avg_cost, 2) AS site_avg_cost, ROUND(fleet_avg_cost, 2) AS fleet_avg_cost, CASE WHEN total_cost > site_avg_cost AND total_cost > fleet_avg_cost THEN 'Above both' WHEN total_cost > site_avg_cost THEN 'Above site' WHEN total_cost > fleet_avg_cost THEN 'Above fleet' ELSE 'Below both' END AS benchmark_status FROM benchmarked ORDER BY total_cost DESC;`, "Window benchmarks compare multiple grains without losing asset detail."),
    H("Executive KPI row", "Scalar subquery dashboard", "Return one row containing fleet size, maintained assets, unresolved orders, maintenance cost, and parts spend.", `SELECT (SELECT COUNT(*) FROM equipment) AS fleet_size, (SELECT COUNT(DISTINCT equipment_id) FROM maintenance_orders) AS maintained_assets, (SELECT COUNT(*) FROM maintenance_orders WHERE status IN ('Open', 'In Progress')) AS unresolved_orders, (SELECT SUM(cost_inr) FROM maintenance_orders) AS maintenance_cost, (SELECT SUM(quantity * unit_cost) FROM spare_part_usage) AS parts_spend;`, "Independent scalar subqueries produce KPIs with different natural grains safely."),
    H("Site risk matrix", "Comprehensive staged design", "Build a site matrix containing fleet size, maintenance assets, unresolved orders, downtime, maintenance cost, parts spend, and a composite risk score.", `WITH site_fleet AS (SELECT site, COUNT(*) AS fleet_size FROM equipment GROUP BY site), parts_by_order AS (SELECT order_id, SUM(quantity * unit_cost) AS parts_spend FROM spare_part_usage GROUP BY order_id), order_facts AS (SELECT e.site, mo.order_id, mo.equipment_id, mo.downtime_hrs, mo.cost_inr, mo.status, COALESCE(p.parts_spend, 0) AS parts_spend FROM maintenance_orders AS mo JOIN equipment AS e ON e.equipment_id = mo.equipment_id LEFT JOIN parts_by_order AS p ON p.order_id = mo.order_id), site_ops AS (SELECT site, COUNT(DISTINCT equipment_id) AS maintained_assets, SUM(CASE WHEN status IN ('Open', 'In Progress') THEN 1 ELSE 0 END) AS unresolved_orders, SUM(downtime_hrs) AS downtime, SUM(cost_inr) AS maintenance_cost, SUM(parts_spend) AS parts_spend FROM order_facts GROUP BY site) SELECT f.site, f.fleet_size, COALESCE(o.maintained_assets, 0) AS maintained_assets, COALESCE(o.unresolved_orders, 0) AS unresolved_orders, COALESCE(o.downtime, 0) AS downtime, COALESCE(o.maintenance_cost, 0) AS maintenance_cost, COALESCE(o.parts_spend, 0) AS parts_spend, ROUND(COALESCE(o.unresolved_orders, 0) * 50 + COALESCE(o.downtime, 0) * 2 + COALESCE(o.maintenance_cost, 0) / 10000.0, 2) AS risk_score FROM site_fleet AS f LEFT JOIN site_ops AS o ON o.site = f.site ORDER BY risk_score DESC, f.site;`, "Each metric is first calculated at a compatible grain, then assembled into the final site-level decision table.")
  ];

  window.SQL_CHALLENGE_BANK = [...beginner, ...intermediate, ...expert, ...hardest].map((challenge, index) => ({
    ...challenge,
    id: index + 1
  }));
})();
